config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post 'confirm_email', to: 'omniauth_callbacks#confirm_email'
  end

  get 'search', to: 'search#index'

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions
      resources :answers
    end
  end

  concern :votable do
    member do
      post 'vote_up'
      post 'vote_down'
      delete 'remove_vote'
    end
  end

  resources :questions, concerns: :votable do
    resources :comments, only: :create, defaults: { commentable: 'questions' }
    resources :answers, concerns: :votable, shallow: true do
      resources :comments, only: :create, defaults: { commentable: 'answers' }
      member do
        post 'best_answer'
      end
    end
    resources :subscriptions, only: [:create, :destroy], shallow:  true
  end

  root 'questions#index'
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Attachable
  include Votable
  include Commentable

  scope :yesterday_created, -> { where(created_at: Time.now.yesterday.all_day) }

  after_create :subscribe_author

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  validates :title, presence: true, length: { maximum: 140 }
  validates :body, :user_id, presence: true

  private

  def subscribe_author
    subscriptions.create(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource

  def index
    @questions = Question.all
    respond_with @questions
  end

  def show
    respond_with @question = Question.find(params[:id])
  end

  def create
    respond_with @question = current_resource_owner.questions.create(question_params)
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_question, only: [:show, :destroy, :update, :check_author]
  before_action :check_author, only: [:update, :destroy]
  before_action :build_answer, only: :show
  after_action  :publish_question, only: :create

  respond_to :js
  respond_to :json, only: :create

  authorize_resource

  def index
    respond_with(@questions = Question.all)
  end

  def new
    respond_with(@question = current_user.questions.new)
  end

  def show
    respond_with @question
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    @question.update(question_params)
    respond_with(@question)
  end

  def destroy
    respond_with(@question.destroy)
  end

  private

  def publish_question
    PrivatePub.publish_to('/questions', question: @question.to_json) if @question.valid?
  end

  def build_answer
    @answer = @question.answers.new
    @answer.attachments.new
  end

  def check_author
    redirect_to @question unless current_user.author_of?(@question)
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer.html.haml
- if answer.valid?
  %li #{answer.body}
  - if current_user && current_user.author_of?(answer)
    = link_to 'Delete answer', question_answer_path(@question, answer), method: :delete

app/views/questions/_form.html.haml
= form_for @question, remote: true, html: { id: "edit-question" } do |f|
  .question-errors
  %p
    = f.label :title, 'Title:'
    = f.text_field :title
  %p
    = f.label :body, 'Body:'
    = f.text_area :body
  = render 'attachments/form', f: f, parent: @question.attachments.new
  = f.submit 'Save'

app/views/questions/_question.html.haml
%h2 #{@question.title}
= render partial: 'votes/vote', locals: { votable: @question }
%p Author: #{@question.user.email}
.panel.panel-default
  .panel-body
    %p #{@question.body}
- if @question.attachments.exists?
  %ul
    - @question.attachments.each do |a|
      %li= link_to a.file.filename, a.file.url
- if current_user && current_user.author_of?(@question)
  = link_to 'Edit question', '', class: 'edit-question-link'
  = link_to 'Delete question', question_path(@question), method: :delete
  = render 'form'
- if current_user
  .subscription
    - if current_user.subscribed_to?(question)
      = button_to 'Unsubscribe', subscription_path(@question.subscriptions.find_by(user_id: current_user.id)),
                               method: :delete, id: 'unsubscribe_button', class: 'btn btn-default', remote: true
    - else
      = button_to 'Subscribe', question_subscriptions_path(@question),
                             method: :post, id: 'subscribe_button', class: 'btn btn-default', remote: true

app/views/questions/index.html.haml
- cache collection_cache_key_for :question do
  .row
    .col-md-10.col-md-offset-1
      %ul.list-group
        - if @questions.present?
          - @questions.each do |question|
            %li.list-group-item= link_to question.title, question_path(question)
        - else
          %h2 No questions yet.
      = link_to 'Add new question', new_question_path

= subscribe_to "/questions"

app/views/questions/new.html.haml
.row
  .col-md-10.col-md-offset-1
    %h2 Add question
    - if @question.errors.any?
      %h2 Some errors:
      %ul
      - @question.errors.full_messages.each do |error|
        %li= error
    = simple_form_for @question do |f|
      = f.input :title
      = f.text_area :body

      = render 'attachments/form', f: f, parent: @question.attachments.new

      = f.button :submit, 'Save'

app/views/questions/show.html.haml
- cache @question do
  .row
    .col-md-10.col-md-offset-1
      %div{id: "question#{@question.id}", class: 'question'}
        = render @question
        %hr
        %p Comments:
        %div{id: "question#{@question.id}-comments"}
          = render @question.comments.order('created_at').includes(:user)
        %div{id: "question#{@question.id}-comments-form", class: "comments-form"}
          = render 'comments/form', commentable: @question
        - if current_user
          = link_to 'Add comment', '', class: 'add-comment-link', data: { commentable_id: @question.id, commentable_type: 'question' }
      %hr
      %h3 Answers:
      #answers{"data-question-id" => "#{@question.id}"}
        = render @question.answers.best_first.includes(:attachments)
      .row
        .col-md-6
          .panel.panel-primary
            .panel-heading
              %h2 Add Answer
            .panel-body
              = render 'answers/form'
      %hr
      = link_to 'Back to questions list', root_path

= subscribe_to "/questions/#{@question.id}/answers"
= subscribe_to '/comments'

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  $('.question-errors').empty()
  <% @question.errors.full_messages.each do |message| %>
    $('.question-errors').append('<%= j message %><br>')
  <% end %>
<% else %>
  $('div#question<%= @question.id %>').replaceWith('<%= j render @question %>');
<% end %>