config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post 'confirm_email', to: 'omniauth_callbacks#confirm_email'
  end

  get 'search', to: 'search#index'

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions
      resources :answers
    end
  end

  concern :votable do
    member do
      post 'vote_up'
      post 'vote_down'
      delete 'remove_vote'
    end
  end

  resources :questions, concerns: :votable do
    resources :comments, only: :create, defaults: { commentable: 'questions' }
    resources :answers, concerns: :votable, shallow: true do
      resources :comments, only: :create, defaults: { commentable: 'answers' }
      member do
        post 'best_answer'
      end
    end
    resources :subscriptions, only: [:create, :destroy], shallow:  true
  end

  root 'questions#index'
end

app/models/search.rb
class Search
  TYPES = %w(all questions answers comments users).freeze

  def self.find(query, type)
    query = Riddle::Query.escape(query)
    return [] unless TYPES.include? type
    type == 'all' ? ThinkingSphinx.search(query) : type.singularize.classify.constantize.search(query)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :load_params, only: :index

  def index
    respond_with @result = Search.find(@query, @type)
  end

  private

  def load_params
    @query = params[:query]
    @type = params[:type]
  end
end

app/views/search/_answer.html.haml
%h4= link_to object.body, question_path(object.question)

app/views/search/_comment.html.haml
- if object.commentable.class.name == 'Question'
  %h4= link_to object.text, question_path(object.commentable)
- else
  %h4= link_to object.text, question_path(object.commentable.question_id)

app/views/search/_form.html.haml
= form_tag search_path, method: :get, class: 'navbar-form navbar-left' do
  = text_field_tag 'query', params[:query], type: 'search', placeholder: 'Search', class: 'form-control'
  = select_tag 'type', options_for_select(Search::TYPES, params[:tpe]), class: 'form-control'
  = submit_tag 'Search', class: 'form-control'

app/views/search/_question.html.haml
%h4= link_to object.title, question_path(object)

app/views/search/_user.html.haml
%h4 #{object.email}

app/views/search/index.html.haml
.row
  .col-md-10.col-md-offset-1
    .panel.panel-default
      .panel-heading
        %h2 Search results:
      .panel-body
        - if @result.any?
          - @result.each do |object|
            %h3 #{object.class.name}
            = render "search/#{object.class.name.underscore}", object: object
        - else
          %h3 Nothing found