config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post 'confirm_email', to: 'omniauth_callbacks#confirm_email'
  end

  get 'search', to: 'search#index'

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions
      resources :answers
    end
  end

  concern :votable do
    member do
      post 'vote_up'
      post 'vote_down'
      delete 'remove_vote'
    end
  end

  resources :questions, concerns: :votable do
    resources :comments, only: :create, defaults: { commentable: 'questions' }
    resources :answers, concerns: :votable, shallow: true do
      resources :comments, only: :create, defaults: { commentable: 'answers' }
      member do
        post 'best_answer'
      end
    end
    resources :subscriptions, only: [:create, :destroy], shallow:  true
  end

  root 'questions#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Attachable
  include Votable
  include Commentable

  belongs_to :user
  belongs_to :question, touch: true

  validates :body, :question_id, :user_id, presence: true

  scope :best_first, -> { order('best DESC', 'created_at').includes(:user) }

  after_create :notify_subscribers

  def make_best!
    transaction do
      question.answers.update_all(best: false)
      update!(best: true)
    end
  end

  def notify_subscribers
    NewAnswerJob.perform_later(self.question)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted
  before_action :authenticate_user!
  before_action :find_question, only: :create
  before_action :find_answer, only: [:update, :destroy, :best_answer]
  before_action :check_author, only: [:update, :destroy]

  respond_to :js

  authorize_resource

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(user: current_user)))
  end

  def update
    respond_with(@answer.update(answer_params))
  end

  def destroy
    respond_with(@answer.destroy)
  end

  def best_answer
    @answer.make_best! if current_user.author_of?(@answer.question)
    redirect_to @answer.question
  end

  private

  def check_author
    redirect_to @answer.question unless current_user.author_of?(@answer)
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource

  def index
    @answers = Answer.all
    respond_with @answers
  end

  def show
    respond_with @answer = Answer.find(params[:id])
  end

  def create
    @question = Question.find(params[:question_id])
    respond_with @answer = @question.answers.create(answer_params.merge(user: current_resource_owner))
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.haml
- if answer.persisted?
  - cache answer do
    %div{id: "answer#{answer.id}"}
      .panel.panel-default
        .panel-heading
          Author: #{answer.user.email}
          = render partial: 'votes/vote', locals: { votable: answer }
          - if answer.best
            %p SOLUTION:
        .panel-body
          %p #{answer.body}
          - if answer.attachments.exists?
            %ul
              - answer.attachments.each do |a|
                %li= link_to a.file.filename, a.file.url
          %hr
          %p Comments:
          %div{id: "answer#{answer.id}-comments"}
            = render answer.comments.order('created_at').includes(:user)
          %div{id: "answer#{answer.id}-comments-form", class: "comments-form"}
            = render 'comments/form', commentable: answer
          - if current_user
            = link_to 'Add comment', '', class: 'add-comment-link', data: { commentable_id: answer.id, commentable_type: 'answer' }
        - if current_user
          .panel-footer
            - if current_user.author_of?(answer.question)
              = link_to 'Solution!', best_answer_answer_path(answer), method: :post
            - if current_user.author_of?(answer)
              = link_to 'Edit answer', '', class: 'edit-answer-link', data: { answer_id: answer.id }
              = link_to 'Delete answer', answer_path(answer), method: :delete, remote: true
              = form_for answer, remote: true, html: { id: "edit-answer#{answer.id}", class: 'edit-answer' } do |f|
                .answer-errors
                = f.text_area :body, label: false, placeholder: 'Answer'
                = f.simple_fields_for :attachments do |a|
                  = render 'attachments/form', f: f
                = f.submit 'Save answer'

app/views/answers/_form.html.haml
= form_for [@question, @answer], remote: true, html: { id: "edit-answer#{@answer.id}" } do |f|
  .answer-errors
  = f.text_area :body, label: false, placeholder: 'Answer'
  = f.fields_for :attachments do |a|
    = render 'attachments/form', f: f
  = f.submit 'Save answer'

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').append('<%= j message %>')
  <% end %>
<% else %>
  $('text_area#answer_body').val('');
  <% publish_to "/questions/#{@question.id}/answers" do %>
    $('#answers').append('<%= j render @answer %>');
  <% end %>
<% end %>

app/views/answers/destroy.js.erb
$('div#answer<%= @answer.id %>').remove()

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').append('<%= j message %>')
  <% end %>
<% else %>
  $('div#answer<%= @answer.id %>').replaceWith('<%= j render @answer %>');
  $('div.panel-body .new-answer #answer_body').val('');
<% end %>